from django.db import models


# ERP項目工事
class ErpItemConstruction(models.Model):
    work_id = models.IntegerField('工事id', blank=True, null=True)
    detail_no = models.IntegerField('明細番号', blank=True, null=True)
    vendor_code = models.CharField('仕入先CD', max_length=10, blank=True, null=True)
    purchase_group_code = models.CharField('購買組織CD', max_length=5, blank=True, null=True)
    purchase_person = models.CharField('購買グループ担当者', max_length=20, blank=True, null=True)
    currency_code = models.CharField('購買グループ担当者', max_length=5, blank=True, null=True)
    account_class = models.CharField('勘定設定', max_length=5, blank=True, null=True)
    item_code = models.CharField('品目CD', max_length=16, blank=True, null=True)
    item_text = models.CharField('品目テキスト', max_length=30, blank=True, null=True)
    order_amount = models.IntegerField('購買発注量', blank=True, null=True)
    ordering_unit = models.CharField('発注単位', max_length=9, blank=True, null=True)
    delivery_date = models.CharField('納入期日', max_length=8, blank=True, null=True)
    amount_per_base_unit = models.CharField('購買価格単位（Per）', max_length=8, blank=True, null=True)
    base_unit_amount = models.CharField('購買価格単位', max_length=8, blank=True, null=True)
    purchase_order_no = models.CharField('購買発注NO ', max_length=10, blank=True, null=True)
    erp_errormsg = models.CharField('ERPエラーメッセージ ', max_length=500, blank=True, null=True)
    item_group_code = models.CharField('品目グループCD', max_length=9, blank=True, null=True)
    plant_code = models.CharField('プラントCD', max_length=4, blank=True, null=True)
    storage_space_code = models.CharField('保管場所CD', max_length=4, blank=True, null=True)
    purchase_trace_no = models.CharField('購買依頼追跡番号', max_length=4, blank=True, null=True)
    order_person = models.CharField('依頼者NTユーザ', max_length=25, blank=True, null=True)
    rem = models.CharField('項目注記2', max_length=50, blank=True, null=True)
    storage_space_rem = models.CharField('納入保管場所注記', max_length=50, blank=True, null=True)
    total_price = models.IntegerField('総額', blank=True, null=True)
    discount_price = models.IntegerField('値引 (金額)', blank=True, null=True)
    account_code = models.CharField('勘定CD', max_length=10, blank=True, null=True)
    cost_center = models.CharField('原価センタ', max_length=10, blank=True, null=True)
    instruction_code = models.CharField('指図書CD', max_length=10, blank=True, null=True)
    consumption_tax_code = models.CharField('消費税コード', max_length=10, blank=True, null=True)
    order_no = models.CharField('購買発注番号', max_length=10, blank=True, null=True)
    relation_no = models.CharField('連携システムNO', max_length=10, blank=True, null=True)
    item_detail_text = models.CharField('明細テキスト', max_length=30, blank=True, null=True)
    construction_start_date = models.CharField('着工予定日', max_length=8, blank=True, null=True)
    budget_id = models.IntegerField('予算id', blank=True, null=True)
    status = models.IntegerField('ステータス', blank=True, null=True)


# ERP工事データ
class ErpConstruction(models.Model):
    order_id = models.IntegerField('依頼id', blank=True, null=True)
    detail_no = models.IntegerField('明細番号', blank=True, null=True)
    budget_id = models.IntegerField('予算id', blank=True, null=True)
    order_date = models.CharField('購買発注日', max_length=8, blank=True, null=True)
    vendor_code = models.CharField('仕入先CD', max_length=10, blank=True, null=True)
    purchase_group_code = models.CharField('購買組織CD', max_length=5, blank=True, null=True)
    purchase_person = models.CharField('購買グループ担当者', max_length=20, blank=True, null=True)
    currency_code = models.CharField('通貨CD', max_length=5, blank=True, null=True)
    account_class = models.CharField('勘定設定', max_length=5, blank=True, null=True)
    item_code = models.CharField('品目CD', max_length=16, blank=True, null=True)
    item_text = models.CharField('品目テキスト', max_length=40, blank=True, null=True)
    order_amount = models.IntegerField('購買発注量', blank=True, null=True)
    ordering_unit = models.CharField('発注単位', max_length=9, blank=True, null=True)
    delivery_date = models.CharField('納入期日', max_length=8, blank=True, null=True)
    amount_per_base_unit = models.CharField('購買価格単位（Per）', max_length=8, blank=True, null=True)
    base_unit_amount = models.CharField('購買価格単位', max_length=8, blank=True, null=True)
    purchase_order_no = models.CharField('購買発注NO ', max_length=10, blank=True, null=True)
    erp_errormsg = models.CharField('ERPエラーメッセージ ', max_length=500, blank=True, null=True)
    item_group_code = models.CharField('品目グループCD', max_length=9, blank=True, null=True)
    item_code_status = models.CharField('品目マスタ登録ステータス', max_length=1, blank=True, null=True)
    plant_code = models.CharField('プラントCD', max_length=4, blank=True, null=True)
    storage_space_code = models.CharField('保管場所CD', max_length=4, blank=True, null=True)
    purchase_trace_no = models.CharField('購買依頼追跡番号', max_length=4, blank=True, null=True)
    order_person = models.CharField('依頼者NTユーザ', max_length=25, blank=True, null=True)
    rem = models.CharField('項目注記2', max_length=50, blank=True, null=True)
    storage_space_rem = models.CharField('納入保管場所注記', max_length=50, blank=True, null=True)
    total_price = models.BigIntegerField('総額', blank=True, null=True)
    discount_price = models.BigIntegerField('値引 (金額)', blank=True, null=True)
    account_code = models.CharField('勘定CD', max_length=10, blank=True, null=True)
    cost_center = models.CharField('原価センタ', max_length=10, blank=True, null=True)
    instruction_code = models.CharField('指図書CD', max_length=10, blank=True, null=True)
    consumption_tax_code = models.CharField('消費税コード', max_length=10, blank=True, null=True)
    order_no = models.CharField('購買発注番号', max_length=10, blank=True, null=True)
    work_class = models.CharField('工事区分', max_length=5, blank=True, null=True)
    relation_no = models.CharField('連携システムNO', max_length=10, blank=True, null=True)
    item_detail_text = models.CharField('明細テキスト', max_length=30, blank=True, null=True)
    construction_start_date = models.CharField('着工予定日', max_length=8, blank=True, null=True)
    status = models.IntegerField('ステータス', blank=True, null=True)
    department = models.CharField('部署', max_length=20, blank=True, null=True)
    division = models.CharField('部門', max_length=20, blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('変更者', max_length=20, blank=True, null=True)
    specification_person_in_charge = models.CharField('仕様書担当者', max_length=20, blank=True, null=True)
    procurement_person_in_charge = models.CharField('調達担当者', max_length=20, blank=True, null=True)
    request_department = models.CharField('依頼部門', max_length=50, blank=True, null=True)


# ERP工事データ
class MCFrame(models.Model):
    order_id = models.IntegerField('依頼id', blank=True, null=True)
    budget_id = models.IntegerField('予算id', blank=True, null=True)
    order_date = models.CharField('購買発注日', max_length=8, blank=True, null=True)
    vendor_code = models.CharField('仕入先CD', max_length=10, blank=True, null=True)
    purchase_group_code = models.CharField('購買組織CD', max_length=5, blank=True, null=True)
    purchase_person = models.CharField('購買グループ担当者', max_length=20, blank=True, null=True)
    currency_code = models.CharField('通貨CD', max_length=5, blank=True, null=True)
    account_class = models.CharField('勘定設定', max_length=5, blank=True, null=True)
    item_code = models.CharField('品目CD', max_length=16, blank=True, null=True)
    item_text = models.CharField('品目テキスト', max_length=40, blank=True, null=True)
    order_amount = models.IntegerField('購買発注量', blank=True, null=True)
    ordering_unit = models.CharField('発注単位', max_length=9, blank=True, null=True)
    delivery_date = models.CharField('納入期日', max_length=8, blank=True, null=True)
    amount_per_base_unit = models.CharField('購買価格単位（Per）', max_length=8, blank=True, null=True)
    base_unit_amount = models.CharField('購買価格単位', max_length=8, blank=True, null=True)
    purchase_order_no = models.CharField('購買発注NO ', max_length=15, blank=True, null=True)
    erp_errormsg = models.CharField('ERPエラーメッセージ ', max_length=500, blank=True, null=True)
    item_group_code = models.CharField('品目グループCD', max_length=9, blank=True, null=True)
    item_code_status = models.CharField('品目マスタ登録ステータス', max_length=1, blank=True, null=True)
    plant_code = models.CharField('プラントCD', max_length=4, blank=True, null=True)
    storage_space_code = models.CharField('保管場所CD', max_length=4, blank=True, null=True)
    purchase_trace_no = models.CharField('購買依頼追跡番号', max_length=4, blank=True, null=True)
    order_person = models.CharField('依頼者NTユーザ', max_length=25, blank=True, null=True)
    rem = models.CharField('項目注記2', max_length=50, blank=True, null=True)
    storage_space_rem = models.CharField('納入保管場所注記', max_length=50, blank=True, null=True)
    total_price = models.BigIntegerField('総額', blank=True, null=True)
    discount_price = models.BigIntegerField('値引 (金額)', blank=True, null=True)
    account_code = models.CharField('勘定CD', max_length=10, blank=True, null=True)
    cost_center = models.CharField('原価センタ', max_length=10, blank=True, null=True)
    instruction_code = models.CharField('指図書CD', max_length=10, blank=True, null=True)
    consumption_tax_code = models.CharField('消費税コード', max_length=10, blank=True, null=True)
    work_class = models.CharField('工事区分', max_length=5, blank=True, null=True)
    relation_no = models.CharField('連携システムNO', max_length=10, blank=True, null=True)
    item_detail_text = models.CharField('明細テキスト', max_length=30, blank=True, null=True)
    construction_start_date = models.CharField('着工予定日', max_length=8, blank=True, null=True)
    status = models.IntegerField('ステータス', blank=True, null=True)
    department = models.CharField('部署', max_length=20, blank=True, null=True)
    division = models.CharField('部門', max_length=20, blank=True, null=True)
    specification_person_in_charge = models.CharField('仕様書担当者', max_length=20, blank=True, null=True)
    procurement_person_in_charge = models.CharField('調達担当者', max_length=20, blank=True, null=True)
    request_department = models.CharField('依頼部門', max_length=50, blank=True, null=True)
    order_no = models.CharField('購買発注番号', max_length=20, blank=True, null=True)
    order_type_classification = models.IntegerField('注文書種類区分', blank=True, null=True)
    numbering = models.IntegerField('ナンバリング', blank=True, null=True)
    year = models.IntegerField('年度', blank=True, null=True)
    detail_no = models.IntegerField('明細番号', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('変更者', max_length=20, blank=True, null=True)


# ERP工事連携エラーデータ
class ErpRelation(models.Model):
    order_id = models.IntegerField('依頼id', blank=True, null=True)
    work_class = models.CharField('工事区分', max_length=5, blank=True, null=True)
    relation_no = models.CharField('連携システムNO', max_length=10, blank=True, null=True)
    erp_errormsg = models.CharField('ERPエラーメッセージ ', max_length=500, blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)

