from django.db import models


# 調達予算情報テーブル
class ProBudgetUnit(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    req_func = models.CharField('要求機能', max_length=20, blank=True, null=True)
    department = models.CharField('部署', max_length=20, blank=True, null=True)
    division = models.CharField('部門', max_length=20, blank=True, null=True)
    jurisdiction_area = models.CharField('所管エリア', max_length=20, blank=True, null=True)
    area_person_in_charge = models.CharField('エリア管理者', max_length=20, blank=True, null=True)
    original_sec_person_in_charge = models.CharField('原課担当者', max_length=20, blank=True, null=True)
    construction_detail = models.CharField('工事内容詳細', max_length=400, blank=True, null=True)
    sche_gov_inspection_date = models.DateField('官庁検査予定日', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    cancel_flag = models.IntegerField('中止FL', blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 調達仕様書情報テーブル
class ProSpecificationUnit(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    work_name = models.CharField('工事名', max_length=70, blank=True, null=True)
    work_charge_process = models.CharField('設備工程', max_length=10, blank=True, null=True)
    req_func = models.CharField('要求機能', max_length=20, blank=True, null=True)
    department = models.CharField('部署', max_length=20, blank=True, null=True)
    division = models.CharField('部門', max_length=20, blank=True, null=True)
    format_kbn = models.CharField('定型/非定型', max_length=20, blank=True, null=True)
    goods_construct_kbn = models.CharField('物品/工事区分', max_length=20, blank=True, null=True)
    specification_person_in_charge = models.CharField('仕様書担当者', max_length=20, blank=True, null=True)
    delivery_location = models.CharField('納入場所', max_length=100, blank=True, null=True)
    desired_construct_period_from = models.DateField('希望工期_FROM', blank=True, null=True)
    desired_construct_period_to = models.DateField('希望工期_TO', blank=True, null=True)
    desired_delivery_date = models.DateField('希望納期日', blank=True, null=True)
    estimate_submission_date = models.DateField('見積提出期日', blank=True, null=True)
    order_limited_date = models.DateField('発注期日', blank=True, null=True)
    scheduled_inspection_date_from = models.DateField('品質/立会検査予定日_FROM', blank=True, null=True)
    scheduled_inspection_date_to = models.DateField('品質/立会検査予定日_TO', blank=True, null=True)
    specification_data = models.CharField('仕様書データ', max_length=100, blank=True, null=True)
    construction_outline = models.CharField('工事概要', max_length=400, blank=True, null=True)
    contents_detail1 = models.CharField('内容詳細1', max_length=3600, blank=True, null=True)
    contents_detail2 = models.CharField('内容詳細2', max_length=3600, blank=True, null=True)
    contents_detail3 = models.CharField('内容詳細3', max_length=3600, blank=True, null=True)
    contents_detail4 = models.CharField('内容詳細4', max_length=3600, blank=True, null=True)
    contents_detail5 = models.CharField('内容詳細5', max_length=3600, blank=True, null=True)
    procurement_person_in_charge = models.CharField('調達担当者', max_length=20, blank=True, null=True)
    management_class_cd = models.CharField('管理区分CD', max_length=2, blank=True, null=True)
    scheduled_acceptance_date_from = models.DateField('品質/受入検査予定日_FROM', blank=True, null=True)
    scheduled_acceptance_date_to = models.DateField('品質/受入検査予定日_TO', blank=True, null=True)
    preparation_delivery_date = models.DateField('引渡準備完了日', blank=True, null=True)
    candidate_vendor1 = models.CharField('候補業者1', max_length=50, blank=True, null=True)
    candidate_vendor2 = models.CharField('候補業者2', max_length=50, blank=True, null=True)
    candidate_vendor3 = models.CharField('候補業者3', max_length=50, blank=True, null=True)
    candidate_vendor4 = models.CharField('候補業者4', max_length=50, blank=True, null=True)
    candidate_vendor5 = models.CharField('候補業者5', max_length=50, blank=True, null=True)
    memo = models.CharField('備考', max_length=400, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    cancel_flag = models.IntegerField('中止FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)
    probable_price = models.BigIntegerField('予想額', blank=True, null=True)
    special_vendor_check = models.BooleanField('特命チェック', blank=True, null=True)
    special_vendor_comment = models.CharField('特命コメント', max_length=400, blank=True, null=True)
    special_vendor_si_comment = models.CharField('調達G特命コメント', max_length=400, blank=True, null=True)


# 調達見積情報テーブル
class ProEstimates(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    candidate_vendor1 = models.CharField('候補業者1', max_length=100, blank=True, null=True)
    maker_name1 = models.CharField('メーカー名1', max_length=100, blank=True, null=True)
    quotation_req_date1 = models.DateField('見積依頼日1', blank=True, null=True)
    estimated_reply_date1 = models.DateField('見積回答期日1', blank=True, null=True)
    delivery_date1_from = models.DateField('工期/納期日1_FROM', blank=True, null=True)
    delivery_date1_to = models.DateField('工期/納期日1_TO', blank=True, null=True)
    last_estimated_amount1 = models.IntegerField('本見積額1', blank=True, null=True)
    last_estimated_discount1 = models.IntegerField('出精値引額1', blank=True, null=True)
    estimated_amount_af_nego1 = models.IntegerField('交渉後見積額1', blank=True, null=True)
    estimated_data1 = models.CharField('見積書データ1', max_length=100, blank=True, null=True)
    eva_delivery_date1 = models.CharField('工期/納期1', max_length=40, blank=True, null=True)
    eva_estimated_valuation_amount1 = models.CharField('見積査定1', max_length=400, blank=True, null=True)
    eva_estimated_assessment_price1 = models.IntegerField('見積査定額1', blank=True, null=True)
    eva_final_price1 = models.CharField('最終金額評価1', max_length=400, blank=True, null=True)
    eva_other1 = models.CharField('その他1', max_length=400, blank=True, null=True)
    candidate_vendor2 = models.CharField('候補業者2', max_length=100, blank=True, null=True)
    maker_name2 = models.CharField('メーカー名2', max_length=100, blank=True, null=True)
    quotation_req_date2 = models.DateField('見積依頼日2', blank=True, null=True)
    estimated_reply_date2 = models.DateField('見積回答期日2', blank=True, null=True)
    delivery_date2_from = models.DateField('工期/納期日2_FROM', blank=True, null=True)
    delivery_date2_to = models.DateField('工期/納期日2_TO', blank=True, null=True)
    last_estimated_amount2 = models.IntegerField('本見積額2', blank=True, null=True)
    last_estimated_discount2 = models.IntegerField('出精値引額2', blank=True, null=True)
    estimated_amount_af_nego2 = models.IntegerField('交渉後見積額2', blank=True, null=True)
    estimated_data2 = models.CharField('見積書データ2', max_length=100, blank=True, null=True)
    eva_delivery_date2 = models.CharField('工期/納期2', max_length=40, blank=True, null=True)
    eva_estimated_valuation_amount2 = models.CharField('見積査定2', max_length=400, blank=True, null=True)
    eva_estimated_assessment_price2 = models.IntegerField('見積査定額2', blank=True, null=True)
    eva_final_price2 = models.CharField('最終金額評価2', max_length=400, blank=True, null=True)
    eva_other2 = models.CharField('その他2', max_length=400, blank=True, null=True)
    candidate_vendor3 = models.CharField('候補業者3', max_length=100, blank=True, null=True)
    maker_name3 = models.CharField('メーカー名3', max_length=100, blank=True, null=True)
    quotation_req_date3 = models.DateField('見積依頼日3', blank=True, null=True)
    estimated_reply_date3 = models.DateField('見積回答期日3', blank=True, null=True)
    delivery_date3_from = models.DateField('工期/納期日3_FROM', blank=True, null=True)
    delivery_date3_to = models.DateField('工期/納期日3_TO', blank=True, null=True)
    last_estimated_amount3 = models.IntegerField('本見積額3', blank=True, null=True)
    last_estimated_discount3 = models.IntegerField('出精値引額3', blank=True, null=True)
    estimated_amount_af_nego3 = models.IntegerField('交渉後見積額3', blank=True, null=True)
    estimated_data3 = models.CharField('見積書データ3', max_length=100, blank=True, null=True)
    eva_delivery_date3 = models.CharField('工期/納期3', max_length=40, blank=True, null=True)
    eva_estimated_valuation_amount3 = models.CharField('見積査定3', max_length=400, blank=True, null=True)
    eva_estimated_assessment_price3 = models.IntegerField('見積査定額3', blank=True, null=True)
    eva_final_price3 = models.CharField('最終金額評価3', max_length=400, blank=True, null=True)
    eva_other3 = models.CharField('その他3', max_length=400, blank=True, null=True)
    candidate_vendor4 = models.CharField('候補業者4', max_length=100, blank=True, null=True)
    maker_name4 = models.CharField('メーカー名4', max_length=100, blank=True, null=True)
    quotation_req_date4 = models.DateField('見積依頼日4', blank=True, null=True)
    estimated_reply_date4 = models.DateField('見積回答期日4', blank=True, null=True)
    delivery_date4_from = models.DateField('工期/納期日4_FROM', blank=True, null=True)
    delivery_date4_to = models.DateField('工期/納期日4_TO', blank=True, null=True)
    last_estimated_amount4 = models.IntegerField('本見積額4', blank=True, null=True)
    last_estimated_discount4 = models.IntegerField('出精値引額4', blank=True, null=True)
    estimated_amount_af_nego4 = models.IntegerField('交渉後見積額4', blank=True, null=True)
    estimated_data4 = models.CharField('見積書データ4', max_length=100, blank=True, null=True)
    eva_delivery_date4 = models.CharField('工期/納期4', max_length=40, blank=True, null=True)
    eva_estimated_valuation_amount4 = models.CharField('見積査定4', max_length=400, blank=True, null=True)
    eva_estimated_assessment_price4 = models.IntegerField('見積査定額4', blank=True, null=True)
    eva_final_price4 = models.CharField('最終金額評価4', max_length=400, blank=True, null=True)
    eva_other4 = models.CharField('その他4', max_length=400, blank=True, null=True)
    candidate_vendor5 = models.CharField('候補業者5', max_length=100, blank=True, null=True)
    maker_name5 = models.CharField('メーカー名5', max_length=100, blank=True, null=True)
    quotation_req_date5 = models.DateField('見積依頼日5', blank=True, null=True)
    estimated_reply_date5 = models.DateField('見積回答期日5', blank=True, null=True)
    delivery_date5_from = models.DateField('工期/納期日5_FROM', blank=True, null=True)
    delivery_date5_to = models.DateField('工期/納期日5_TO', blank=True, null=True)
    last_estimated_amount5 = models.IntegerField('本見積額5', blank=True, null=True)
    last_estimated_discount5 = models.IntegerField('出精値引額5', blank=True, null=True)
    estimated_amount_af_nego5 = models.IntegerField('交渉後見積額5', blank=True, null=True)
    estimated_data5 = models.CharField('見積書データ5', max_length=100, blank=True, null=True)
    eva_delivery_date5 = models.CharField('工期/納期5', max_length=40, blank=True, null=True)
    eva_estimated_valuation_amount5 = models.CharField('見積査定5', max_length=400, blank=True, null=True)
    eva_estimated_assessment_price5 = models.IntegerField('見積査定額5', blank=True, null=True)
    eva_final_price5 = models.CharField('最終金額評価5', max_length=400, blank=True, null=True)
    eva_other5 = models.CharField('その他5', max_length=400, blank=True, null=True)
    confirmed_vendor = models.CharField('確定業者', max_length=100, blank=True, null=True)
    confirmed_last_estimated_amount = models.IntegerField('確定本見積額', blank=True, null=True)
    confirmed_estimated_amount_af_nego = models.IntegerField('確定交渉後見積額', blank=True, null=True)
    estimated_deadline_date = models.DateField('決定見積提出期日', blank=True, null=True)
    fixed_delivery_date = models.DateField('決定納期', blank=True, null=True)
    fixed_delivery_date_from = models.DateField('決定工期_FROM', blank=True, null=True)
    fixed_delivery_date_to = models.DateField('決定工期_TO', blank=True, null=True)
    fixed_delivery_location = models.CharField('決定納入場所', max_length=100, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 工事業者評価テーブル
class ProVendorEvaluation(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    estimate_assessment_evaluation_sum = models.CharField('見積査定評価まとめ', max_length=400, blank=True, null=True)
    candidate_vendor_comment1 = models.CharField('候補業者1コメント', max_length=400, blank=True, null=True)
    candidate_vendor_comment2 = models.CharField('候補業者2コメント', max_length=400, blank=True, null=True)
    candidate_vendor_comment3 = models.CharField('候補業者3コメント', max_length=400, blank=True, null=True)
    candidate_vendor_comment4 = models.CharField('候補業者4コメント', max_length=400, blank=True, null=True)
    candidate_vendor_comment5 = models.CharField('候補業者5コメント', max_length=400, blank=True, null=True)
    eva_final_price = models.CharField('最終金額評価', max_length=400, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 個別契約書類管理テーブル
class ProIndividualContractDoc(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    order_classification = models.CharField('注文分類', max_length=20, blank=True, null=True)
    tax_kbn = models.CharField('課税', max_length=20, blank=True, null=True)
    order_issuance_date = models.DateField('注文書発行日', blank=True, null=True)
    order_creator = models.CharField('注文書作成者', max_length=20, blank=True, null=True)
    item_code = models.CharField('品目コード', max_length=20, blank=True, null=True)
    item_group = models.CharField('品目グループ', max_length=20, blank=True, null=True)
    payment_terms = models.CharField('支払い条件', max_length=20, blank=True, null=True)
    individual_contract_terms = models.CharField('個別契約条件', max_length=20, blank=True, null=True)
    order_no = models.IntegerField('注文番号', blank=True, null=True)
    construction_classification = models.CharField('工事分類', max_length=20, blank=True, null=True)
    order_data = models.CharField('注文書データ', max_length=100, blank=True, null=True)
    order_confirmation_data = models.CharField('注文請書データ', max_length=100, blank=True, null=True)
    numbering = models.IntegerField('ナンバリング', blank=True, null=True)
    vendor_code = models.CharField('仕入先CD', max_length=10, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 工事検査結果テーブル
class ProInspectionResults(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    order_classification_from = models.DateField('品質/立会検査実施日_FROM', blank=True, null=True)
    order_classification_to = models.DateField('品質/立会検査実施日_TO', blank=True, null=True)
    inspection_results = models.CharField('検査結果', max_length=400, blank=True, null=True)
    inspection_date = models.CharField('品質/立会検査結果データ', max_length=100, blank=True, null=True)
    judge_kbn = models.CharField('判定区分', max_length=20, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 工事納入情報テーブル
class ProDelivery(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    scheduled_date = models.DateField('工事(納入)予定日', blank=True, null=True)
    scheduled_datime = models.DateTimeField('工事(納入)時刻', blank=True, null=True)
    delivery_date = models.DateField('納入日', blank=True, null=True)
    storage_loc = models.CharField('保管場所', max_length=400, blank=True, null=True)
    delivery_note_data = models.CharField('納品書データ', max_length=100, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 工事準備情報テーブル
class ProConstructionPrep(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    delivery_prep_period_from = models.DateField('引渡準備期間_FROM', blank=True, null=True)
    delivery_prep_period_to = models.DateField('引渡準備期間_TO', blank=True, null=True)
    prep_contents = models.CharField('準備内容', max_length=400, blank=True, null=True)
    prep_result = models.CharField('準備結果', max_length=20, blank=True, null=True)
    implementation_department = models.CharField('実施部署', max_length=20, blank=True, null=True)
    execution_department_manager = models.CharField('実施部署責任者', max_length=20, blank=True, null=True)
    memo = models.CharField('備考', max_length=400, blank=True, null=True)
    delivery_prep_completion_date = models.DateField('引渡準備完了日', blank=True, null=True)
    required_procedure = models.CharField('必要手続き', max_length=20, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)


# 工事品質結果テーブル
class ProConstructionQualityResults(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    quality_inspection_result = models.CharField('品質検査結果', max_length=20, blank=True, null=True)
    production_permit_date = models.DateField('生産許可日', blank=True, null=True)
    memo = models.CharField('備考欄', max_length=400, blank=True, null=True)
    submitted_doc = models.CharField('提出資料データ', max_length=100, blank=True, null=True)
    date_of_receipt_of_submitted_materials = models.DateField('提出資料受領日', blank=True, null=True)
    submitted_doc_memo = models.CharField('提出書類の備考欄', max_length=400, blank=True, null=True)
    check_result = models.CharField('提出書類の内容確認結果', max_length=20, blank=True, null=True)
    completion_notification = models.CharField('竣工届データ', max_length=100, blank=True, null=True)
    acceptance_date = models.DateField('検収実施日', blank=True, null=True)
    receipt = models.CharField('検収書電子データ', max_length=100, blank=True, null=True)
    receipt_sending_date = models.DateField('検収書送付日', blank=True, null=True)
    invoice = models.CharField('請求書電子データ', max_length=100, blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)
    construction_completion_date = models.DateField('工事完了日', blank=True, null=True)


# 工事検査結果(受入)テーブル
class ProInspectionAcceptance(models.Model):
    budget_id = models.IntegerField('予算ID', blank=True, null=True)
    rev_no = models.IntegerField('RevNO', blank=True, null=True)
    budget_no = models.CharField('予算NO', max_length=20, blank=True, null=True)
    budget_name = models.CharField('予算名', max_length=70, blank=True, null=True)
    construction_id = models.IntegerField('工事ID', blank=True, null=True)
    sub_id = models.IntegerField('サブNO', blank=True, null=True)
    order_classification_from = models.DateField('品質/受入検査実施日_FROM', blank=True, null=True)
    order_classification_to = models.DateField('品質/受入検査実施日_TO', blank=True, null=True)
    inspection_results = models.CharField('検査結果', max_length=400, blank=True, null=True)
    inspection_date = models.CharField('品質/受入検査結果データ', max_length=40, blank=True, null=True)
    judge_kbn = models.CharField('判定区分', max_length=20, blank=True, null=True)
    entry_on_progress_flag = models.IntegerField('登録中FL', blank=True, null=True)
    lost_flag = models.IntegerField('無効FL', blank=True, null=True)
    entry_datetime = models.DateTimeField('登録日時', blank=True, null=True)
    entry_operator = models.CharField('登録者', max_length=20, blank=True, null=True)
    update_datetime = models.DateTimeField('更新日時', blank=True, null=True)
    update_operator = models.CharField('更新者', max_length=20, blank=True, null=True)
