# Generated by Django 2.1.15 on 2023-02-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('department_cd', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部署CD')),
                ('department_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='部署名')),
                ('division_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='部門CD')),
                ('jurisdiction_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='所管エリア')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('division_cd', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部門CD')),
                ('division_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='部門名')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='ユーザーid')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='ユーザー名')),
                ('department', models.CharField(blank=True, max_length=10, null=True, verbose_name='部署')),
                ('division', models.CharField(blank=True, max_length=10, null=True, verbose_name='部門')),
                ('authority', models.CharField(blank=True, max_length=10, null=True, verbose_name='権限')),
                ('confirm_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='確認者')),
                ('permit_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='承認者')),
                ('department_charge_flag', models.CharField(blank=True, max_length=10, null=True, verbose_name='部署担当フラグ')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('user_order', models.IntegerField(blank=True, null=True, verbose_name='部署内表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='area_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fms.User', verbose_name='エリア担当者'),
        ),
    ]
