# Generated by Django 2.1.15 on 2023-02-17 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMaster',
            fields=[
                ('action', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='作業CD')),
                ('action_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業名')),
                ('action_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業属性')),
                ('action_authority', models.IntegerField(blank=True, null=True, verbose_name='作業権限')),
                ('progress_transition', models.IntegerField(blank=True, null=True, verbose_name='進捗遷移')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_action',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table_id', models.IntegerField(blank=True, null=True, verbose_name='対象ID')),
                ('operation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='作業日時')),
                ('operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業者')),
                ('operator_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業者部署')),
                ('comment', models.CharField(blank=True, max_length=800, null=True, verbose_name='コメント')),
                ('action', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.ActionMaster', verbose_name='作業CD')),
            ],
            options={
                'db_table': 't_log',
            },
        ),
        migrations.CreateModel(
            name='PageMaster',
            fields=[
                ('page', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ページID')),
                ('page_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='ページ名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_page',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=20, null=True, verbose_name='対象')),
                ('present_division', models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業部門')),
                ('present_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業部署')),
                ('present_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業者')),
            ],
            options={
                'db_table': 't_progress',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='所管評価レベル')),
                ('judgement', models.CharField(blank=True, max_length=40, null=True, verbose_name='判定')),
                ('results', models.CharField(blank=True, max_length=1000, null=True, verbose_name='対策検討結果')),
                ('evaluation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更結果評価')),
            ],
            options={
                'db_table': 't_quality',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=40, null=True, verbose_name='部門名')),
                ('department', models.CharField(blank=True, max_length=40, null=True, verbose_name='部署名')),
                ('user', models.CharField(blank=True, max_length=40, null=True, verbose_name='申請者')),
                ('change_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='変更対象')),
                ('others', models.CharField(blank=True, max_length=40, null=True, verbose_name='その他')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='変更管理名称')),
                ('outline', models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更内容概略')),
                ('level', models.CharField(blank=True, max_length=40, null=True, verbose_name='継続/一過性')),
                ('treatment', models.CharField(blank=True, max_length=40, null=True, verbose_name='リスク低減処置')),
                ('safety_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='評価レベル_安全面')),
                ('quality_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='評価レベル_品質面')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='変更希望日')),
                ('delivery_date_start', models.DateField(blank=True, null=True, verbose_name='変更日開始')),
                ('delivery_date_end', models.DateField(blank=True, null=True, verbose_name='変更日終了')),
                ('level2', models.CharField(blank=True, max_length=40, null=True, verbose_name='継続/一過性')),
                ('others2', models.CharField(blank=True, max_length=40, null=True, verbose_name='その他')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('application_date', models.DateField(blank=True, default=datetime.datetime(2023, 2, 17, 14, 36, 31, 258757), null=True, verbose_name='申請日')),
                ('education_management_system_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='教育管理システムID')),
            ],
            options={
                'db_table': 't_request',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='所管評価レベル')),
                ('judgement', models.CharField(blank=True, max_length=40, null=True, verbose_name='判定')),
                ('results', models.CharField(blank=True, max_length=1000, null=True, verbose_name='対策検討結果')),
                ('evaluation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更結果評価')),
                ('request', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.Request', verbose_name='依頼ID')),
            ],
            options={
                'db_table': 't_safety',
            },
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業属性')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('action', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.ActionMaster', verbose_name='作業CD')),
            ],
            options={
                'db_table': 'm_step_action',
            },
        ),
        migrations.CreateModel(
            name='StepChargeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='担当部署')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_step_charge_department',
            },
        ),
        migrations.CreateModel(
            name='StepDisplayPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(blank=True, null=True, verbose_name='ページNO')),
                ('default_page', models.IntegerField(blank=True, null=True, verbose_name='初期ページ')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PageMaster', verbose_name='ページID')),
            ],
            options={
                'db_table': 'm_step_display_page',
            },
        ),
        migrations.CreateModel(
            name='StepMaster',
            fields=[
                ('step', models.IntegerField(primary_key=True, serialize=False, verbose_name='工程ID')),
                ('step_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='工程名')),
                ('hidden_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_step',
            },
        ),
        migrations.CreateModel(
            name='StepPageEntryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('page', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.PageMaster', verbose_name='ページID')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.StepMaster', verbose_name='工程ID')),
            ],
            options={
                'db_table': 'm_step_page_entry',
            },
        ),
        migrations.CreateModel(
            name='StepRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='進行方向')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steprelation_next_step', to='app.StepMaster', verbose_name='次工程ID')),
                ('present_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steprelation_present_step', to='app.StepMaster', verbose_name='工程ID')),
            ],
            options={
                'db_table': 'm_step_relation',
            },
        ),
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('target', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='対象')),
                ('target_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='対象名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_target',
            },
        ),
        migrations.AddField(
            model_name='steppageentrymaster',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.TargetMaster', verbose_name='対象'),
        ),
        migrations.AddField(
            model_name='stepdisplaypage',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='stepchargedepartment',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='stepchargedepartment',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.TargetMaster', verbose_name='対象'),
        ),
        migrations.AddField(
            model_name='stepaction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='quality',
            name='request',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.Request', verbose_name='依頼ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_last_step', to='app.StepMaster', verbose_name='前工程ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='present_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_present_step', to='app.StepMaster', verbose_name='現工程ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='request',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.Request', verbose_name='依頼ID'),
        ),
        migrations.AddField(
            model_name='log',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='log',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='app.TargetMaster', verbose_name='対象'),
        ),
    ]
