# Generated by Django 2.1.15 on 2023-02-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('target', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='対象')),
                ('target_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='対象名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_target',
            },
        ),
    ]
