# Generated by Django 2.1.15 on 2023-03-28 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 28, 11, 55, 49, 925709), null=True, verbose_name='申請日'),
        ),
    ]
