# Generated by Django 2.1.15 on 2023-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmaster',
            name='authority',
            field=models.IntegerField(blank=True, null=True, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='申請日'),
        ),
    ]
