# Generated by Django 2.1.15 on 2023-03-28 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0002_auto_20230328_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 28, 13, 42, 38, 370276), null=True, verbose_name='申請日'),
        ),
    ]
