# Generated by Django 2.1.15 on 2023-03-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0003_auto_20230328_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 28, 15, 53, 0, 444397), null=True, verbose_name='申請日'),
        ),
    ]
