# Generated by Django 2.1.15 on 2023-03-28 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0005_auto_20230328_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 28, 16, 3, 8, 996767), null=True, verbose_name='申請日'),
        ),
    ]
